In [40]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

with open('newflipkart.html','r',encoding='utf-8') as file:
    html_content=file.read()
soup=BeautifulSoup(html_content)
# print(soup.prettify())
box=soup.findAll('a',class_='CGtC98')
# print(box)
name=[]
memory=[]
color=[]
stars=[]
review=[]
op=[]
np=[]
discount=[]
for i in box:
    a=(i.find('div',class_='KzDlHZ').get_text()).split('(')
    name.append(a[0].strip())
    b=a[1].split('(')[0].split(',')
    color.append(b[0])
    memory.append(b[1].strip().split(')')[0])
    stars.append(i.find('span',class_='Y1HWO0').get_text())
    review.append(i.find('span',class_='Wphh3N').get_text().split('&\xa0')[1].split()[0])
    op.append(i.find('div',class_='Nx9bqj _4b5DiR').text[1:].replace(',',''))
    np.append(i.find('div',class_='yRaY8j ZYYwLA').text[1:].replace(',',''))
    discount.append(i.find('div',class_='UkUFwK').text.split('%')[0]+'%')
# print(np)
d={'name':name,'color':color,'memory':memory,'stars':stars,'review':review,'old_price':op,'new_price':np,'discount':discount}
df=pd.DataFrame(d)
df

,name,color,memory,stars,review,old_price,new_price,discount
0,Apple iPhone 16,Black,128 GB,4.6,704,74900,79900,6%
1,Apple iPhone 16,Pink,128 GB,4.6,704,74900,79900,6%
2,Apple iPhone 13,Starlight,128 GB,4.6,"13,902",44999,49900,9%
3,Apple iPhone 16,White,128 GB,4.6,704,74900,79900,6%
4,Apple iPhone 16 Plus,White,128 GB,4.6,143,84900,89900,5%
5,Apple iPhone 16e,White,128 GB,4.6,51,54900,59900,8%
6,Apple iPhone 16,Teal,128 GB,4.6,704,74900,79900,6%
7,Apple iPhone 16 Plus,Black,128 GB,4.6,143,84900,89900,5%
8,Apple iPhone 13,Midnight,128 GB,4.6,"13,902",44999,49900,9%
9,Apple iPhone 13,Blue,128 GB,4.6,"13,902",44999,49900,9%
10,Apple iPhone 16,Ultramarine,128 GB,4.6,704,74900,79900,6%
11,Apple iPhone 15,Blue,128 GB,4.6,"9,296",64400,69900,7%
12,Apple iPhone 16,Black,256 GB,4.6,704,84900,89900,5%
13,Apple iPhone 16,Ultramarine,256 GB,4.6,704,84900,89900,5%
14,Apple iPhone 14,Starlight,128 GB,4.6,"11,672",54999,59900,8%
15,Apple iPhone 16,Pink,256 GB,4.6,704,84900,89900,5%
16,Apple iPhone 16,White,256 GB,4.6,704,84900,89900,5%
17,Apple iPhone 15 Plus,Green,256 GB,4.6,"2,541",84900,89900,5%
18,Apple iPhone 16 Pro,Desert Titanium,256 GB,4.7,104,122900,129900,5%
19,Apple iPhone 16 Plus,Ultramarine,256 GB,4.6,143,94900,99900,5%
20,Apple iPhone 16,Teal,256 GB,4.6,704,84900,89900,5%
21,Apple iPhone 16 Plus,Teal,128 GB,4.6,143,84900,89900,5%
22,Apple iPhone 16 Plus,Pink,256 GB,4.6,143,94900,99900,5%
23,Apple iPhone 15,Pink,256 GB,4.6,"9,296",74400,79900,6%

In [91]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

with open('TrumpLies.html','r',encoding='utf-8') as file:
    html_content=file.read()
soup=BeautifulSoup(html_content)
# print(soup.prettify())
# box=soup.findAll('a',class_='CGtC98')
# # print(box)
box=soup.find('head')
print('title:',box.find('title').get_text(strip=True))

b1=soup.find('h1',class_='custom-hed story-heading interactive-headline').text
title=''
for i in b1:
    title=title+i.strip()
print(title) 

b2=soup.find('footer',class_='m-statement__footer').text
date=b2.split('😊')[1].strip()
print(date)

b3=soup.find('p',class_='secret-word').text
sw=b3
print(sw)

b4=soup.findAll('h1')
h1=[]
for i in b4:
    h1.append(i.get_text(strip=True))
print(h1)
b5=soup.findAll('h2')
h2=[]
for i in b5:
    h2.append(i.get_text(strip=True))
print(h2)

b6=soup.findAll('a',href=True)
links=[]
for link in b6: 
    if (link['href'].startswith('http') or link['href'].startswith('https')):
        links.append(link['href'])
# print(links)

b7=soup.findAll('span',class_='short-desc')
print(len(b7))

date=[]
statement=[]
text=[]
for i in b7:
    d=i.find('strong').get_text(strip=True)
    s=i.get_text(strip=True).split('“')[1].split('”')[0].replace('"','')
    t=i.find('span',class_='short-truth').get_text(strip=True)[1:].replace(')','')
    date.append(d)
    statement.append(s)
    text.append(t)
#     print('Date:',d)
#     print('statement:',s)
#     print('Text:',t)
#     print('--------------')

d={'Date':date,'statement':statement,'text':text}
df=pd.DataFrame(d)
df

title Opinion | President Trump’s Lies, the Definitive List - The New York Times
Trump’sLies
August 15, 1947
blackpink
['President Trump’s Lies, the Definitive List', 'Trump’sLies']
['Opinion', 'Site Information Navigation']
180

,Date,statement,text
0,Jan. 21,I wasn't a fan of Iraq. I didn't want to go in...,He was for an invasion before he was against it.
1,Jan. 21,A reporter for Time magazine — and I have been...,Trump was on the cover 11 times and Nixon appe...
2,Jan. 23,Between 3 million and 5 million illegal votes ...,There's no evidence of illegal voting.
3,Jan. 25,"Now, the audience was the biggest ever. But th...",Official aerial photos show Obama's 2009 inaug...
4,Jan. 25,Take a look at the Pew reports (which show vot...,The report never mentioned voter fraud.
...,...,...,...
175,Oct. 25,We have trade deficits with almost everybody.,We have trade surpluses with more than 100 cou...
176,Oct. 27,"Wacky & totally unhinged Tom Steyer, who has b...",Steyer has financially supported many winning ...
177,Nov. 1,"Again, we're the highest-taxed nation, just ab...",We're not.
178,Nov. 7,When you look at the city with the strongest g...,"Several other cities, including New York and L..."
179,Nov. 11,"I'd rather have him – you know, work with him...","There is no evidence that Democrats ""set up"" R..."